import requests
from bs4 import BeautifulSoup
import os
from urllib.parse import urljoin, urlparse

# Configuration for multiple target websites
TARGET_SITES = {
    # Academic and Research
    "https://arxiv.org/": "https://arxiv.org/",
    "https://eric.ed.gov/": "https://eric.ed.gov/",
    "https://www.jstor.org/": "https://www.jstor.org/",
    "https://pubmed.ncbi.nlm.nih.gov/": "https://pubmed.ncbi.nlm.nih.gov/",
    "https://www.researchgate.net/": "https://www.researchgate.net/",
    "https://scholar.google.com/": "https://scholar.google.com/",
    "https://www.semanticscholar.org/": "https://www.semanticscholar.org/",
    "https://www.nature.com/": "https://www.nature.com/",
    "https://www.science.org/": "https://www.science.org/",
    "https://plos.org/": "https://plos.org/",
    "https://www.springer.com/": "https://www.springer.com/",
    "https://www.sciencedirect.com/": "https://www.sciencedirect.com/",
    "https://ieeexplore.ieee.org/": "https://ieeexplore.ieee.org/",
    "https://dl.acm.org/": "https://dl.acm.org/",
    "https://academic.oup.com/": "https://academic.oup.com/",
    "https://link.springer.com/": "https://link.springer.com/",
    "https://www.tandfonline.com/": "https://www.tandfonline.com/",
    "https://www.cambridge.org/core": "https://www.cambridge.org/core",
    "https://www.biorxiv.org/": "https://www.biorxiv.org/",
    "https://www.medrxiv.org/": "https://www.medrxiv.org/",
    "https://www.ncbi.nlm.nih.gov/pmc/": "https://www.ncbi.nlm.nih.gov/pmc/",
    "https://citeseerx.ist.psu.edu/": "https://citeseerx.ist.psu.edu/",
    "https://www.scopus.com/": "https://www.scopus.com/",
    "https://www.webofscience.com/": "https://www.webofscience.com/",
    "https://www.mdpi.com/": "https://www.mdpi.com/",
    "https://journals.plos.org/": "https://journals.plos.org/",
    "https://openaccess.thecvf.com/": "https://openaccess.thecvf.com/",
    "https://www.ssrn.com/": "https://www.ssrn.com/",
    "https://www.econstor.eu/": "https://www.econstor.eu/",
    "https://www.scielo.org/": "https://www.scielo.org/",
    "https://hal.science/": "https://hal.science/",
    "https://psycnet.apa.org/": "https://psycnet.apa.org/",
    "https://www.proquest.com/": "https://www.proquest.com/",
    "https://repec.org/": "https://repec.org/",
    "https://www.oecd-ilibrary.org/": "https://www.oecd-ilibrary.org/",
    "https://www.osti.gov/": "https://www.osti.gov/",
    "https://www.hindawi.com/": "https://www.hindawi.com/",
    "https://journals.sagepub.com/": "https://journals.sagepub.com/",
    "https://www.pnas.org/": "https://www.pnas.org/",
    "https://www.cell.com/": "https://www.cell.com/",
    "https://www.frontiersin.org/": "https://www.frontiersin.org/",
    "https://www.rsc.org/journals-books-databases/": "https://www.rsc.org/journals-books-databases/",
    "https://www.wiley.com/en-us/journals": "https://www.wiley.com/en-us/journals",
    "https://www.ingentaconnect.com/": "https://www.ingentaconnect.com/",

    # Blogs and Forums
    "https://www.blogger.com/": "https://www.blogger.com/",
    "https://dev.to/": "https://dev.to/",
    "https://hashnode.com/": "https://hashnode.com/",
    "https://medium.com/": "https://medium.com/",
    "https://quora.com/": "https://quora.com/",
    "https://www.reddit.com/r/programming/": "https://www.reddit.com/",
    "https://www.tripadvisor.com/": "https://www.tripadvisor.com/",
    "https://substack.com/": "https://substack.com/",
    "https://www.tumblr.com/": "https://www.tumblr.com/",
    "https://wordpress.com/": "https://wordpress.com/",
    "https://ghost.org/": "https://ghost.org/",
    "https://news.ycombinator.com/": "https://news.ycombinator.com/",
    "https://stackexchange.com/": "https://stackexchange.com/",
    "https://stackoverflow.com/": "https://stackoverflow.com/",
    "https://www.lobste.rs/": "https://lobste.rs/",
    "https://www.producthunt.com/": "https://www.producthunt.com/",
    "https://www.metafilter.com/": "https://www.metafilter.com/",
    "https://www.xda-developers.com/": "https://www.xda-developers.com/",
    "https://www.daniweb.com/": "https://www.daniweb.com/",
    "https://www.chess.com/forum": "https://www.chess.com/forum",
    "https://forums.macrumors.com/": "https://forums.macrumors.com/",
    "https://forums.androidcentral.com/": "https://forums.androidcentral.com/",
    "https://www.discourse.org/": "https://www.discourse.org/",
    "https://www.wattpad.com/": "https://www.wattpad.com/",
    "https://www.livejournal.com/": "https://www.livejournal.com/",
    "https://www.cnet.com/forums/": "https://www.cnet.com/forums/",
    "https://www.fodors.com/community/": "https://www.fodors.com/community/",
    "https://www.reddit.com/r/science/": "https://www.reddit.com/r/science/",
    "https://www.reddit.com/r/askscience/": "https://www.reddit.com/r/askscience/",
    "https://forum.arduino.cc/": "https://forum.arduino.cc/",
    "https://slickdeals.net/forums/": "https://slickdeals.net/forums/",
    "https://www.flyertalk.com/forum/": "https://www.flyertalk.com/forum/",
    "https://www.bodybuilding.com/forums/": "https://www.bodybuilding.com/forums/",
    "https://forums.tomshardware.com/": "https://forums.tomshardware.com/",
    "https://forum.unity.com/": "https://forum.unity.com/",
    "https://community.spiceworks.com/": "https://community.spiceworks.com/",
    "https://community.letsencrypt.org/": "https://community.letsencrypt.org/",
    "https://discuss.python.org/": "https://discuss.python.org/",
    "https://forums.gentoo.org/": "https://forums.gentoo.org/",
    "https://www.blenderartists.org/": "https://blenderartists.org/",
    "https://www.gardenweb.com/discussions": "https://www.gardenweb.com/discussions",
    
    # E-commerce and Popular Sites
    "https://www.amazon.com/": "https://www.amazon.com/",
    "https://www.ebay.com/": "https://www.ebay.com/",
    "https://www.target.com/": "https://www.target.com/",
    "https://www.walmart.com/": "https://www.walmart.com/",
    "https://www.bestbuy.com/": "https://www.bestbuy.com/",
    "https://www.costco.com/": "https://www.costco.com/",
    "https://www.homedepot.com/": "https://www.homedepot.com/",
    "https://www.lowes.com/": "https://www.lowes.com/",
    "https://www.etsy.com/": "https://www.etsy.com/",
    "https://www.shopify.com/": "https://www.shopify.com/",
    "https://www.alibaba.com/": "https://www.alibaba.com/",
    "https://www.aliexpress.com/": "https://www.aliexpress.com/",
    "https://www.flipkart.com/": "https://www.flipkart.com/",
    "https://www.rakuten.com/": "https://www.rakuten.com/",
    "https://www.zappos.com/": "https://www.zappos.com/",
    "https://www.newegg.com/": "https://www.newegg.com/",
    "https://www.overstock.com/": "https://www.overstock.com/",
    "https://www.macys.com/": "https://www.macys.com/",
    "https://www.kohls.com/": "https://www.kohls.com/",
    "https://www.ulta.com/": "https://www.ulta.com/",
    "https://www.sephora.com/": "https://www.sephora.com/",
    "https://www.wayfair.com/": "https://www.wayfair.com/",
    "https://www.bhphotovideo.com/": "https://www.bhphotovideo.com/",
    "https://www.samsclub.com/": "https://www.samsclub.com/",
    "https://www.groupon.com/": "https://www.groupon.com/",
    "https://www.chewy.com/": "https://www.chewy.com/",
    "https://www.rei.com/": "https://www.rei.com/",
    "https://www.booking.com/": "https://www.booking.com/",
    "https://www.expedia.com/": "https://www.expedia.com/",
    "https://www.ticketmaster.com/": "https://www.ticketmaster.com/",
    "https://www.priceline.com/": "https://www.priceline.com/",
    "https://www.hotels.com/": "https://www.hotels.com/",
    "https://www.ubereats.com/": "https://www.ubereats.com/",
    "https://www.doordash.com/": "https://www.doordash.com/",
    "https://www.grubhub.com/": "https://www.grubhub.com/",
    "https://www.instacart.com/": "https://www.instacart.com/",
    "https://www.wish.com/": "https://www.wish.com/",
    "https://www.vivino.com/": "https://www.vivino.com/",
    "https://www.stubhub.com/": "https://www.stubhub.com/",
    "https://www.ticketswap.com/": "https://www.ticketswap.com/",
    "https://www.fandango.com/": "https://www.fandango.com/",
    "https://www.qvc.com/": "https://www.qvc.com/",
    "https://www.crateandbarrel.com/": "https://www.crateandbarrel.com/",
    "https://www.potterybarn.com/": "https://www.potterybarn.com/",
    "https://www.mercari.com/": "https://www.mercari.com/",
    "https://www.offerup.com/": "https://www.offerup.com/",
    "https://www.carvana.com/": "https://www.carvana.com/",
    "https://www.autotrader.com/": "https://www.autotrader.com/",
    
    # Educational and Reference
    "https://www.codecademy.com/": "https://www.codecademy.com/",
    "https://www.coursera.org/": "https://www.coursera.org/",
    "https://developer.mozilla.org/en-US/": "https://developer.mozilla.org/",
    "https://docs.python.org/3/": "https://docs.python.org/",
    "https://www.edx.org/": "https://www.edx.org/",
    "https://www.freecodecamp.org/": "https://www.freecodecamp.org/",
    "https://www.geeksforgeeks.org/": "https://www.geeksforgeeks.org/",
    "https://www.khanacademy.org/": "https://www.khanacademy.org/",
    "https://www.udemy.com/": "https://www.udemy.com/",
    "https://www.w3schools.com/": "https://www.w3schools.com/",
    "https://www.pluralsight.com/": "https://www.pluralsight.com/",
    "https://www.skillshare.com/": "https://www.skillshare.com/",
    "https://www.lynda.com/": "https://www.lynda.com/",
    "https://www.udacity.com/": "https://www.udacity.com/",
    "https://www.masterclass.com/": "https://www.masterclass.com/",
    "https://brilliant.org/": "https://brilliant.org/",
    "https://www.duolingo.com/": "https://www.duolingo.com/",
    "https://www.alison.com/": "https://www.alison.com/",
    "https://www.memrise.com/": "https://www.memrise.com/",
    "https://ocw.mit.edu/": "https://ocw.mit.edu/",
    "https://openstax.org/": "https://openstax.org/",
    "https://academicearth.org/": "https://academicearth.org/",
    "https://www.futurelearn.com/": "https://www.futurelearn.com/",
    "https://www.saylor.org/": "https://www.saylor.org/",
    "https://www.open.edu/openlearn/": "https://www.open.edu/openlearn/",
    "https://www.britannica.com/": "https://www.britannica.com/",
    "https://www.sparknotes.com/": "https://www.sparknotes.com/",
    "https://www.chegg.com/": "https://www.chegg.com/",
    "https://www.chegg.com/study": "https://www.chegg.com/study",
    "https://www.coursehero.com/": "https://www.coursehero.com/",
    "https://www.quizlet.com/": "https://www.quizlet.com/",
    "https://www.dictionary.com/": "https://www.dictionary.com/",
    "https://www.thesaurus.com/": "https://www.thesaurus.com/",
    "https://www.investopedia.com/": "https://www.investopedia.com/",
    "https://www.howtogeek.com/": "https://www.howtogeek.com/",
    "https://www.ted.com/": "https://www.ted.com/",
    "https://www.litcharts.com/": "https://www.litcharts.com/",
    "https://www.shmoop.com/": "https://www.shmoop.com/",
    "https://www.bartleby.com/": "https://www.bartleby.com/",
    "https://www.enotes.com/": "https://www.enotes.com/",
    "https://www.infoplease.com/": "https://www.infoplease.com/",
    "https://www.mathsisfun.com/": "https://www.mathsisfun.com/",
    "https://www.purplemath.com/": "https://www.purplemath.com/",
    "https://www.symbolab.com/": "https://www.symbolab.com/",
    "https://www.kiddle.co/": "https://www.kiddle.co/",
    "https://www.refseek.com/": "https://www.refseek.com/",
    "https://www.ck12.org/": "https://www.ck12.org/",
    "https://www.nationalgeographic.org/education/": "https://www.nationalgeographic.org/education/",
    "https://www.si.edu/learn": "https://www.si.edu/learn",
    "https://www.merriam-webster.com/": "https://www.merriam-webster.com/",
    "https://www.bbc.co.uk/bitesize/": "https://www.bbc.co.uk/bitesize/",
    
    # Entertainment and Social
    "https://www.cnet.com/": "https://www.cnet.com/",
    "https://www.gamespot.com/": "https://www.gamespot.com/",
    "https://www.ign.com/": "https://www.ign.com/",
    "https://www.imdb.com/": "https://www.imdb.com/",
    "https://www.instagram.com/": "https://www.instagram.com/",
    "https://www.pinterest.com/": "https://www.pinterest.com/",
    "https://www.rottentomatoes.com/": "https://www.rottentomatoes.com/",
    "https://www.tiktok.com/": "https://www.tiktok.com/",
    "https://www.youtube.com/": "https://www.youtube.com/",
    "https://www.twitch.tv/": "https://www.twitch.tv/",
    "https://www.spotify.com/": "https://www.spotify.com/",
    "https://www.netflix.com/": "https://www.netflix.com/",
    "https://www.hulu.com/": "https://www.hulu.com/",
    "https://www.discord.com/": "https://www.discord.com/",
    "https://www.steam.com/": "https://www.steam.com/",
    "https://www.epicgames.com/": "https://www.epicgames.com/",
    "https://www.polygon.com/": "https://www.polygon.com/",
    "https://kotaku.com/": "https://kotaku.com/",
    "https://www.metacritic.com/": "https://www.metacritic.com/",
    "https://www.fandom.com/": "https://www.fandom.com/",
    "https://www.goodreads.com/": "https://www.goodreads.com/",
    "https://letterboxd.com/": "https://letterboxd.com/",
    "https://www.soundcloud.com/": "https://www.soundcloud.com/",
    "https://www.audible.com/": "https://www.audible.com/",
    "https://www.bandcamp.com/": "https://www.bandcamp.com/",
    "https://www.allmusic.com/": "https://www.allmusic.com/",
    "https://www.deviantart.com/": "https://www.deviantart.com/",
    "https://www.tumblr.com/": "https://www.tumblr.com/",
    "https://www.flickr.com/": "https://www.flickr.com/",
    "https://www.myanimelist.net/": "https://www.myanimelist.net/",
    "https://www.crunchyroll.com/": "https://www.crunchyroll.com/",
    "https://www.vimeo.com/": "https://www.vimeo.com/",
    "https://www.dailymotion.com/": "https://www.dailymotion.com/",
    "https://www.reddit.com/r/movies/": "https://www.reddit.com/r/movies/",
    "https://www.reddit.com/r/music/": "https://www.reddit.com/r/music/",
    "https://www.memecenter.com/": "https://www.memecenter.com/",
    "https://www.boredpanda.com/": "https://www.boredpanda.com/",
    "https://www.tvtropes.org/": "https://www.tvtropes.org/",
    "https://www.geek.com/": "https://www.geek.com/",
    "https://www.9gag.com/": "https://www.9gag.com/",
    "https://www.patreon.com/": "https://www.patreon.com/",
    "https://www.facebook.com/": "https://www.facebook.com/",
    "https://www.twitter.com/": "https://www.twitter.com/",
    "https://www.snapchat.com/": "https://www.snapchat.com/",
    "https://www.vk.com/": "https://www.vk.com/",
    "https://www.tumblr.com/": "https://www.tumblr.com/",
    "https://www.periscope.tv/": "https://www.periscope.tv/",
    "https://www.dlive.tv/": "https://www.dlive.tv/",
    "https://www.peacocktv.com/": "https://www.peacocktv.com/",
    "https://www.paramountplus.com/": "https://www.paramountplus.com/",
    "https://www.hbomax.com/": "https://www.hbomax.com/",
    "https://www.disneyplus.com/": "https://www.disneyplus.com/",
    "https://www.apple.com/apple-tv-plus/": "https://www.apple.com/apple-tv-plus/",
    
    # News and Media
    "https://abcnews.go.com/": "https://abcnews.go.com/",
    "https://www.apnews.com/": "https://www.apnews.com/",
    "https://www.bbc.com/news": "https://www.bbc.com/",
    "https://www.bloomberg.com/": "https://www.bloomberg.com/",
    "https://www.cbsnews.com/": "https://www.cbsnews.com/",
    "https://www.cnn.com/": "https://www.cnn.com/",
    "https://www.cnbc.com/": "https://www.cnbc.com/",
    "https://www.forbes.com/": "https://www.forbes.com/",
    "https://www.huffpost.com/": "https://www.huffpost.com/",
    "https://www.nytimes.com/": "https://www.nytimes.com/",
    "https://www.reuters.com/": "https://www.reuters.com/",
    "https://www.usatoday.com/": "https://www.usatoday.com/",
    "https://www.washingtonpost.com/": "https://www.washingtonpost.com/",
    "https://www.wsj.com/": "https://www.wsj.com/",
    "https://www.npr.org/": "https://www.npr.org/",
    "https://www.pbs.org/": "https://www.pbs.org/",
    "https://www.time.com/": "https://www.time.com/",
    "https://www.newsweek.com/": "https://www.newsweek.com/",
    "https://www.axios.com/": "https://www.axios.com/",
    "https://www.politico.com/": "https://www.politico.com/",
    "https://www.thehill.com/": "https://www.thehill.com/",
    "https://www.vox.com/": "https://www.vox.com/",
    "https://www.vice.com/": "https://www.vice.com/",
    "https://www.buzzfeed.com/": "https://www.buzzfeed.com/",
    "https://www.nbcnews.com/": "https://www.nbcnews.com/",
    "https://www.latimes.com/": "https://www.latimes.com/",
    "https://www.sfgate.com/": "https://www.sfgate.com/",
    "https://www.chicagotribune.com/": "https://www.chicagotribune.com/",
    "https://www.economist.com/": "https://www.economist.com/",
    "https://www.ft.com/": "https://www.ft.com/",
    "https://www.theguardian.com/": "https://www.theguardian.com/",
    "https://www.aljazeera.com/": "https://www.aljazeera.com/",
    "https://www.sciencenews.org/": "https://www.sciencenews.org/",
    "https://www.nature.com/news/": "https://www.nature.com/news/",
    "https://www.techcrunch.com/": "https://www.techcrunch.com/",
    "https://www.engadget.com/": "https://www.engadget.com/",
    "https://www.wired.com/": "https://www.wired.com/",
    "https://www.slashdot.org/": "https://www.slashdot.org/",
    "https://www.theverge.com/": "https://www.theverge.com/",
    "https://www.mashable.com/": "https://www.mashable.com/",
    "https://arstechnica.com/": "https://arstechnica.com/",
    "https://www.politifact.com/": "https://www.politifact.com/",
    "https://www.snopes.com/": "https://www.snopes.com/",
    "https://www.propublica.org/": "https://www.propublica.org/",
    "https://www.scientificamerican.com/": "https://www.scientificamerican.com/",
    "https://www.nationalgeographic.com/": "https://www.nationalgeographic.com/",
    "https://www.bostonglobe.com/": "https://www.bostonglobe.com/",
    "https://www.dw.com/": "https://www.dw.com/",
    "https://globalnews.ca/": "https://globalnews.ca/",
    "https://www.cbc.ca/news": "https://www.cbc.ca/news",
    "https://www.smh.com.au/": "https://www.smh.com.au/",
    "https://www.japantimes.co.jp/": "https://www.japantimes.co.jp/",
    "https://www.lemonde.fr/": "https://www.lemonde.fr/",
    "https://www.elpais.com/": "https://www.elpais.com/",
    "https://www.independent.co.uk/": "https://www.independent.co.uk/",
    "https://www.thedailybeast.com/": "https://www.thedailybeast.com/",
    "https://www.newyorker.com/": "https://www.newyorker.com/",
    
    # Technology and Programming Sites
    "https://arstechnica.com/": "https://arstechnica.com/",
    "https://www.bleepingcomputer.com/": "https://www.bleepingcomputer.com/",
    "https://github.com/trending": "https://github.com/",
    "https://kernel.org/": "https://www.kernel.org/",
    "https://www.linuxquestions.org/": "https://www.linuxquestions.org/",
    "https://www.maketecheasier.com/": "https://www.maketecheasier.com/",
    "https://news.ycombinator.com/": "https://news.ycombinator.com/",
    "https://stackoverflow.com/": "https://stackoverflow.com/",
    "https://techcrunch.com/": "https://techcrunch.com/",
    "https://www.theverge.com/": "https://www.theverge.com/",
    "https://en.wikipedia.org/wiki/Main_Page": "https://en.wikipedia.org/wiki/",
    "https://xda-developers.com/": "https://xda-developers.com/",
    "https://www.wired.com/": "https://www.wired.com/",
    "https://www.engadget.com/": "https://www.engadget.com/",
    "https://www.tomshardware.com/": "https://www.tomshardware.com/",
    "https://www.anandtech.com/": "https://www.anandtech.com/",
    "https://www.pcworld.com/": "https://www.pcworld.com/",
    "https://www.computerworld.com/": "https://www.computerworld.com/",
    "https://www.infoworld.com/": "https://www.infoworld.com/",
    "https://www.zdnet.com/": "https://www.zdnet.com/",
    "https://www.techmeme.com/": "https://www.techmeme.com/",
    "https://slashdot.org/": "https://slashdot.org/",
    "https://www.hackernoon.com/": "https://www.hackernoon.com/",
    "https://www.dzone.com/": "https://www.dzone.com/",
    "https://css-tricks.com/": "https://css-tricks.com/",
    "https://codepen.io/": "https://codepen.io/",
    "https://jsfiddle.net/": "https://jsfiddle.net/",
    "https://replit.com/": "https://replit.com/",
    "https://codesandbox.io/": "https://codesandbox.io/",
    "https://glitch.com/": "https://glitch.com/",
    "https://www.hackerrank.com/": "https://www.hackerrank.com/",
    "https://leetcode.com/": "https://leetcode.com/",
    "https://www.codewars.com/": "https://www.codewars.com/",
    "https://www.topcoder.com/": "https://www.topcoder.com/",
    "https://codeforces.com/": "https://codeforces.com/",
    
    # AI and Machine Learning
    "https://openai.com/": "https://openai.com/",
    "https://www.anthropic.com/": "https://www.anthropic.com/",
    "https://huggingface.co/": "https://huggingface.co/",
    "https://www.tensorflow.org/": "https://www.tensorflow.org/",
    "https://pytorch.org/": "https://pytorch.org/",
    "https://scikit-learn.org/": "https://scikit-learn.org/",
    "https://www.kaggle.com/": "https://www.kaggle.com/",
    "https://papers.withcode.com/": "https://papers.withcode.com/",
    "https://distill.pub/": "https://distill.pub/",
    "https://towardsdatascience.com/": "https://towardsdatascience.com/",
    "https://machinelearningmastery.com/": "https://machinelearningmastery.com/",
    "https://www.deeplearning.ai/": "https://www.deeplearning.ai/",
    "https://deepmind.com/": "https://deepmind.com/",
    "https://ai.google/": "https://ai.google/",
    "https://ai.facebook.com/": "https://ai.facebook.com/",
    "https://microsoft.com/en-us/ai": "https://microsoft.com/en-us/ai",
    "https://mlcommons.org/": "https://mlcommons.org/",
    "https://colab.research.google.com/": "https://colab.research.google.com/",
    "https://www.fast.ai/": "https://www.fast.ai/",
    "https://www.mlflow.org/": "https://www.mlflow.org/",
    "https://mlops.community/": "https://mlops.community/",
    "https://ai.stackexchange.com/": "https://ai.stackexchange.com/",
    "https://arxiv-sanity.com/": "https://arxiv-sanity.com/",
    "https://aiweekly.co/": "https://aiweekly.co/",
    "https://www.datasciencecentral.com/": "https://www.datasciencecentral.com/",
    "https://neptune.ai/": "https://neptune.ai/",
    "https://www.analyticsvidhya.com/": "https://www.analyticsvidhya.com/",
    "https://datafloq.com/": "https://datafloq.com/",
    "https://deeplearning.net/": "https://deeplearning.net/",
    "https://www.ibm.com/watson/": "https://www.ibm.com/watson/",
    "https://ai.ibm.com/": "https://ai.ibm.com/",
    "https://www.singularitynet.io/": "https://www.singularitynet.io/",
    "https://ai.googleblog.com/": "https://ai.googleblog.com/",
    "https://www.elementai.com/": "https://www.elementai.com/",
    "https://www.nvidia.com/en-us/deep-learning-ai/": "https://www.nvidia.com/en-us/deep-learning-ai/",
    "https://www.baai.ac.cn/": "https://www.baai.ac.cn/",
    "https://allenai.org/": "https://allenai.org/",
    "https://aitopics.org/": "https://aitopics.org/",
    "https://datascience.stackexchange.com/": "https://datascience.stackexchange.com/",
    "https://www.topbots.com/": "https://www.topbots.com/",
    "https://paperwithcode.com/": "https://paperwithcode.com/",
    "https://www.researchgate.net/": "https://www.researchgate.net/",
    "https://www.zeta-alpha.com/": "https://www.zeta-alpha.com/",
    "https://www.mlperf.org/": "https://www.mlperf.org/",
    "https://www.kdnuggets.com/": "https://www.kdnuggets.com/",
    "https://www.abbyy.com/ai/": "https://www.abbyy.com/ai/",
    "https://www.datarobot.com/": "https://www.datarobot.com/",
    "https://www.coursera.org/browse/data-science/machine-learning": "https://www.coursera.org/browse/data-science/machine-learning",
    "https://www.microsoft.com/en-us/research/research-area/artificial-intelligence/": "https://www.microsoft.com/en-us/research/research-area/artificial-intelligence/",
    "https://www.kaggle.com/datasets": "https://www.kaggle.com/datasets",
    "https://registry.opendata.aws/": "https://registry.opendata.aws/",
    "https://datahub.io/": "https://datahub.io/",
    "https://datasetsearch.research.google.com/": "https://datasetsearch.research.google.com/",
    "https://www.openml.org/": "https://www.openml.org/",
    
    # Cloud and DevOps
    "https://aws.amazon.com/": "https://aws.amazon.com/",
    "https://cloud.google.com/": "https://cloud.google.com/",
    "https://azure.microsoft.com/": "https://azure.microsoft.com/",
    "https://www.digitalocean.com/": "https://www.digitalocean.com/",
    "https://www.linode.com/": "https://www.linode.com/",
    "https://www.vultr.com/": "https://www.vultr.com/",
    "https://www.heroku.com/": "https://www.heroku.com/",
    "https://vercel.com/": "https://vercel.com/",
    "https://netlify.com/": "https://netlify.com/",
    "https://www.docker.com/": "https://www.docker.com/",
    "https://kubernetes.io/": "https://kubernetes.io/",
    "https://www.jenkins.io/": "https://www.jenkins.io/",
    "https://github.com/actions": "https://github.com/",
    "https://gitlab.com/": "https://gitlab.com/",
    "https://bitbucket.org/": "https://bitbucket.org/",
    "https://circleci.com/": "https://circleci.com/",
    "https://travis-ci.com/": "https://travis-ci.com/",
    "https://www.ansible.com/": "https://www.ansible.com/",
    "https://www.terraform.io/": "https://www.terraform.io/",
    "https://www.packer.io/": "https://www.packer.io/",
    "https://www.chef.io/": "https://www.chef.io/",
    "https://puppet.com/": "https://puppet.com/",
    "https://saltproject.io/": "https://saltproject.io/",
    "https://www.cloudflare.com/": "https://www.cloudflare.com/",
    "https://www.nginx.com/": "https://www.nginx.com/",
    "https://prometheus.io/": "https://prometheus.io/",
    "https://grafana.com/": "https://grafana.com/",
    "https://www.datadoghq.com/": "https://www.datadoghq.com/",
    "https://newrelic.com/": "https://newrelic.com/",
    "https://www.splunk.com/": "https://www.splunk.com/",
    "https://www.elastic.co/": "https://www.elastic.co/",
    "https://www.sonarqube.org/": "https://www.sonarqube.org/",
    "https://argoproj.github.io/": "https://argoproj.github.io/",
    "https://openshift.com/": "https://openshift.com/",
    "https://rancher.com/": "https://rancher.com/",
    "https://www.hashicorp.com/": "https://www.hashicorp.com/",
    "https://www.atlassian.com/software/bamboo": "https://www.atlassian.com/software/bamboo",
    "https://www.spinnaker.io/": "https://www.spinnaker.io/",
    "https://www.mesosphere.com/": "https://www.mesosphere.com/",
    "https://fly.io/": "https://fly.io/",
    "https://render.com/": "https://render.com/",
    "https://www.serverless.com/": "https://www.serverless.com/",
    "https://www.consul.io/": "https://www.consul.io/",
    "https://www.nomadproject.io/": "https://www.nomadproject.io/",
    
    # Design and Creative
    "https://www.behance.net/": "https://www.behance.net/",
    "https://dribbble.com/": "https://dribbble.com/",
    "https://www.figma.com/": "https://www.figma.com/",
    "https://www.adobe.com/": "https://www.adobe.com/",
    "https://www.canva.com/": "https://www.canva.com/",
    "https://unsplash.com/": "https://unsplash.com/",
    "https://www.pexels.com/": "https://www.pexels.com/",
    "https://pixabay.com/": "https://pixabay.com/",
    "https://www.shutterstock.com/": "https://www.shutterstock.com/",
    "https://www.gettyimages.com/": "https://www.gettyimages.com/",
    "https://www.creativebloq.com/": "https://www.creativebloq.com/",
    "https://www.deviantart.com/": "https://www.deviantart.com/",
    "https://www.coroflot.com/": "https://www.coroflot.com/",
    "https://99designs.com/": "https://99designs.com/",
    "https://www.logopond.com/": "https://www.logopond.com/",
    "https://fontawesome.com/": "https://fontawesome.com/",
    "https://fonts.google.com/": "https://fonts.google.com/",
    "https://fontstruct.com/": "https://fontstruct.com/",
    "https://www.dafont.com/": "https://www.dafont.com/",
    "https://thenounproject.com/": "https://thenounproject.com/",
    "https://icons8.com/": "https://icons8.com/",
    "https://coolors.co/": "https://coolors.co/",
    "https://colorhunt.co/": "https://colorhunt.co/",
    "https://www.uplabs.com/": "https://www.uplabs.com/",
    "https://www.pinterest.com/categories/design/": "https://www.pinterest.com/categories/design/",
    "https://www.invisionapp.com/": "https://www.invisionapp.com/",
    "https://www.sketch.com/": "https://www.sketch.com/",
    "https://www.coreldraw.com/": "https://www.coreldraw.com/",
    "https://www.blender.org/": "https://www.blender.org/",
    "https://www.autodesk.com/": "https://www.autodesk.com/",
    "https://www.cgtrader.com/": "https://www.cgtrader.com/",
    "https://www.turbosquid.com/": "https://www.turbosquid.com/",
    "https://www.artstation.com/": "https://www.artstation.com/",
    "https://www.flaticon.com/": "https://www.flaticon.com/",
    "https://lottiefiles.com/": "https://lottiefiles.com/",
    "https://www.motionarray.com/": "https://www.motionarray.com/",
    "https://www.vecteezy.com/": "https://www.vecteezy.com/",
    "https://www.graphicburger.com/": "https://www.graphicburger.com/",
    "https://www.mockupworld.co/": "https://www.mockupworld.co/",
    "https://www.humaaans.com/": "https://www.humaaans.com/",
    "https://www.pixelbuddha.net/": "https://www.pixelbuddha.net/",
    "https://www.designspiration.com/": "https://www.designspiration.com/",
    "https://www.materialpalette.com/": "https://www.materialpalette.com/",
    "https://www.subtlepatterns.com/": "https://www.subtlepatterns.com/",
    "https://www.pixeden.com/": "https://www.pixeden.com/",
    "https://www.iconmonstr.com/": "https://www.iconmonstr.com/",
    "https://www.brusheezy.com/": "https://www.brusheezy.com/",
    
    # Finance and Business
    "https://www.investopedia.com/": "https://www.investopedia.com/",
    "https://finance.yahoo.com/": "https://finance.yahoo.com/",
    "https://www.marketwatch.com/": "https://www.marketwatch.com/",
    "https://www.fool.com/": "https://www.fool.com/",
    "https://www.morningstar.com/": "https://www.morningstar.com/",
    "https://www.sec.gov/": "https://www.sec.gov/",
    "https://www.nasdaq.com/": "https://www.nasdaq.com/",
    "https://www.nyse.com/": "https://www.nyse.com/",
    "https://www.entrepreneur.com/": "https://www.entrepreneur.com/",
    "https://www.inc.com/": "https://www.inc.com/",
    "https://hbr.org/": "https://hbr.org/",
    "https://www.fastcompany.com/": "https://www.fastcompany.com/",
    "https://www.businessinsider.com/": "https://www.businessinsider.com/",
    "https://www.cnbc.com/business/": "https://www.cnbc.com/business/",
    "https://www.barrons.com/": "https://www.barrons.com/",
    "https://www.bloomberg.com/businessweek": "https://www.bloomberg.com/businessweek",
    "https://www.wsj.com/": "https://www.wsj.com/",
    "https://www.economist.com/": "https://www.economist.com/",
    "https://www.ft.com/": "https://www.ft.com/",
    "https://www.reuters.com/business/": "https://www.reuters.com/business/",
    "https://www.forbes.com/business/": "https://www.forbes.com/business/",
    "https://www.investing.com/": "https://www.investing.com/",
    "https://www.seekingalpha.com/": "https://www.seekingalpha.com/",
    "https://www.kiplinger.com/": "https://www.kiplinger.com/",
    "https://www.nerdwallet.com/": "https://www.nerdwallet.com/",
    "https://www.creditkarma.com/": "https://www.creditkarma.com/",
    "https://www.bankrate.com/": "https://www.bankrate.com/",
    "https://www.valuepenguin.com/": "https://www.valuepenguin.com/",
    "https://www.sba.gov/": "https://www.sba.gov/",
    "https://www.worldbank.org/": "https://www.worldbank.org/",
    "https://www.imf.org/": "https://www.imf.org/",
    "https://www.oecd.org/": "https://www.oecd.org/",
    "https://www.crowdfundinsider.com/": "https://www.crowdfundinsider.com/",
    "https://www.cbinsights.com/": "https://www.cbinsights.com/",
    "https://www.crunchbase.com/": "https://www.crunchbase.com/",
    "https://pitchbook.com/": "https://pitchbook.com/",
    "https://angel.co/": "https://angel.co/",
    "https://www.macrotrends.net/": "https://www.macrotrends.net/",
    "https://www.federalreserve.gov/": "https://www.federalreserve.gov/",
    "https://fred.stlouisfed.org/": "https://fred.stlouisfed.org/",
    "https://www.spglobal.com/": "https://www.spglobal.com/",
    "https://www.moody's.com/": "https://www.moody's.com/",
    "https://www.statista.com/": "https://www.statista.com/",
    "https://www.privco.com/": "https://www.privco.com/",
    "https://www.plainsite.org/": "https://www.plainsite.org/",
    "https://www.edgar-online.com/": "https://www.edgar-online.com/",
    
    # Health and Lifestyle
    "https://www.webmd.com/": "https://www.webmd.com/",
    "https://www.mayoclinic.org/": "https://www.mayoclinic.org/",
    "https://www.healthline.com/": "https://www.healthline.com/",
    "https://www.medicalnewstoday.com/": "https://www.medicalnewstoday.com/",
    "https://www.nih.gov/": "https://www.nih.gov/",
    "https://www.cdc.gov/": "https://www.cdc.gov/",
    "https://www.who.int/": "https://www.who.int/",
    "https://www.goodhousekeeping.com/": "https://www.goodhousekeeping.com/",
    "https://www.allrecipes.com/": "https://www.allrecipes.com/",
    "https://www.foodnetwork.com/": "https://www.foodnetwork.com/",
    "https://www.tasteofhome.com/": "https://www.tasteofhome.com/",
    "https://www.epicurious.com/": "https://www.epicurious.com/",
    "https://www.clevelandclinic.org/": "https://www.clevelandclinic.org/",
    "https://www.medscape.com/": "https://www.medscape.com/",
    "https://www.hopkinsmedicine.org/": "https://www.hopkinsmedicine.org/",
    "https://www.drugs.com/": "https://www.drugs.com/",
    "https://www.psychologytoday.com/": "https://www.psychologytoday.com/",
    "https://www.nami.org/": "https://www.nami.org/",
    "https://www.eatright.org/": "https://www.eatright.org/",
    "https://www.self.com/": "https://www.self.com/",
    "https://www.shape.com/": "https://www.shape.com/",
    "https://www.menshealth.com/": "https://www.menshealth.com/",
    "https://www.womenshealthmag.com/": "https://www.womenshealthmag.com/",
    "https://www.runnersworld.com/": "https://www.runnersworld.com/",
    "https://www.livestrong.com/": "https://www.livestrong.com/",
    "https://www.sleepfoundation.org/": "https://www.sleepfoundation.org/",
    "https://www.yummly.com/": "https://www.yummly.com/",
    "https://myfitnesspal.com/": "https://myfitnesspal.com/",
    "https://www.spoonacular.com/": "https://www.spoonacular.com/",
    "https://www.headspace.com/": "https://www.headspace.com/",
    "https://www.calm.com/": "https://www.calm.com/",
    "https://www.mindbodygreen.com/": "https://www.mindbodygreen.com/",
    "https://www.verywellfit.com/": "https://www.verywellfit.com/",
    "https://www.verywellmind.com/": "https://www.verywellmind.com/",
    "https://www.everydayhealth.com/": "https://www.everydayhealth.com/",
    "https://www.samhsa.gov/": "https://www.samhsa.gov/",
    "https://www.mentalhealth.gov/": "https://www.mentalhealth.gov/",
    "https://www.parents.com/": "https://www.parents.com/",
    "https://www.bhg.com/": "https://www.bhg.com/",
    "https://www.realsimple.com/": "https://www.realsimple.com/",
    "https://www.cookinglight.com/": "https://www.cookinglight.com/",
    "https://www.delish.com/": "https://www.delish.com/",
    "https://www.simplyrecipes.com/": "https://www.simplyrecipes.com/",
    "https://www.savoryexperiments.com/": "https://www.savoryexperiments.com/",
    "https://www.skinnytaste.com/": "https://www.skinnytaste.com/",
    
    # Travel and Geography
    "https://www.booking.com/": "https://www.booking.com/",
    "https://www.expedia.com/": "https://www.expedia.com/",
    "https://www.airbnb.com/": "https://www.airbnb.com/",
    "https://www.kayak.com/": "https://www.kayak.com/",
    "https://www.skyscanner.com/": "https://www.skyscanner.com/",
    "https://www.lonelyplanet.com/": "https://www.lonelyplanet.com/",
    "https://www.nationalgeographic.com/": "https://www.nationalgeographic.com/",
    "https://www.atlasobscura.com/": "https://www.atlasobscura.com/",
    "https://www.tripadvisor.com/": "https://www.tripadvisor.com/",
    "https://www.trivago.com/": "https://www.trivago.com/",
    "https://www.agoda.com/": "https://www.agoda.com/",
    "https://www.hotels.com/": "https://www.hotels.com/",
    "https://www.rome2rio.com/": "https://www.rome2rio.com/",
    "https://www.viator.com/": "https://www.viator.com/",
    "https://www.roughguides.com/": "https://www.roughguides.com/",
    "https://www.fodors.com/": "https://www.fodors.com/",
    "https://www.travelandleisure.com/": "https://www.travelandleisure.com/",
    "https://www.cntraveler.com/": "https://www.cntraveler.com/",
    "https://www.natgeokids.com/": "https://www.natgeokids.com/",
    "https://earth.google.com/": "https://earth.google.com/",
    "https://maps.google.com/": "https://maps.google.com/",
    "https://www.openstreetmap.org/": "https://www.openstreetmap.org/",
    "https://www.wikivoyage.org/": "https://www.wikivoyage.org/",
    "https://www.timeanddate.com/worldclock/": "https://www.timeanddate.com/worldclock/",
    "https://www.couchsurfing.com/": "https://www.couchsurfing.com/",
    "https://www.tourradar.com/": "https://www.tourradar.com/",
    "https://www.roadtrippers.com/": "https://www.roadtrippers.com/",
    "https://www.travelmath.com/": "https://www.travelmath.com/",
    "https://www.budgetyourtrip.com/": "https://www.budgetyourtrip.com/",
    "https://www.romeartlover.it/": "https://www.romeartlover.it/",
    "https://www.greatcirclemapper.net/": "https://www.greatcirclemapper.net/",
    "https://www.flightaware.com/": "https://www.flightaware.com/",
    "https://www.flightstats.com/": "https://www.flightstats.com/",
    "https://www.tripit.com/": "https://www.tripit.com/",
    "https://www.wanderlog.com/": "https://www.wanderlog.com/",
    "https://www.bing.com/maps": "https://www.bing.com/maps",
    "https://www.geoguessr.com/": "https://www.geoguessr.com/",
    "https://www.earthcam.com/": "https://www.earthcam.com/",
    "https://www.tourismthailand.org/": "https://www.tourismthailand.org/",
    "https://www.visitbritain.com/": "https://www.visitbritain.com/",
    "https://www.australia.com/": "https://www.australia.com/",
    "https://www.japan.travel/en/": "https://www.japan.travel/en/",
    
    # Government and Legal
    "https://www.usa.gov/": "https://www.usa.gov/",
    "https://www.congress.gov/": "https://www.congress.gov/",
    "https://www.whitehouse.gov/": "https://www.whitehouse.gov/",
    "https://www.supremecourt.gov/": "https://www.supremecourt.gov/",
    "https://www.fbi.gov/": "https://www.fbi.gov/",
    "https://www.irs.gov/": "https://www.irs.gov/",
    "https://www.fda.gov/": "https://www.fda.gov/",
    "https://www.epa.gov/": "https://www.epa.gov/",
    "https://www.nsa.gov/": "https://www.nsa.gov/",
    "https://www.state.gov/": "https://www.state.gov/",
    "https://www.cia.gov/": "https://www.cia.gov/",
    "https://www.loc.gov/": "https://www.loc.gov/",
    "https://www.census.gov/": "https://www.census.gov/",
    "https://www.nps.gov/": "https://www.nps.gov/",
    "https://www.gao.gov/": "https://www.gao.gov/",
    "https://www.sec.gov/": "https://www.sec.gov/",
    "https://www.ssa.gov/": "https://www.ssa.gov/",
    "https://www.bls.gov/": "https://www.bls.gov/",
    "https://data.gov/": "https://data.gov/",
    "https://www.usajobs.gov/": "https://www.usajobs.gov/",
    "https://www.justice.gov/": "https://www.justice.gov/",
    "https://www.gpo.gov/": "https://www.gpo.gov/",
    "https://www.uspto.gov/": "https://www.uspto.gov/",
    "https://www.fcc.gov/": "https://www.fcc.gov/",
    "https://www.treasury.gov/": "https://www.treasury.gov/",
    "https://www.dot.gov/": "https://www.dot.gov/",
    "https://www.dol.gov/": "https://www.dol.gov/",
    "https://www.hud.gov/": "https://www.hud.gov/",
    "https://www.eeoc.gov/": "https://www.eeoc.gov/",
    "https://www.uscis.gov/": "https://www.uscis.gov/",
    "https://www.nlm.nih.gov/": "https://www.nlm.nih.gov/",
    "https://www.law.cornell.edu/": "https://www.law.cornell.edu/",
    "https://www.oig.hhs.gov/": "https://www.oig.hhs.gov/",
    "https://www.un.org/": "https://www.un.org/",
    "https://www.europa.eu/": "https://www.europa.eu/",
    "https://www.europarl.europa.eu/": "https://www.europarl.europa.eu/",
    "https://www.parliament.uk/": "https://www.parliament.uk/",
    "https://www.canada.ca/en.html": "https://www.canada.ca/en.html",
    "https://www.australia.gov.au/": "https://www.australia.gov.au/",
    "https://www.supremecourt.ca/": "https://www.supremecourt.ca/",
    "https://www.gov.uk/": "https://www.gov.uk/",
    "https://www.supremecourt.uk/": "https://www.supremecourt.uk/",
    "https://www.oireachtas.ie/en/": "https://www.oireachtas.ie/en/",
    "https://www.gov.za/": "https://www.gov.za/",
    
    # Utilities and Tools
    "https://archive.org/": "https://archive.org/",
    "https://translate.google.com/": "https://translate.google.com/",
    "https://maps.google.com/": "https://maps.google.com/",
    "https://www.google.com/": "https://www.google.com/",
    "https://www.bing.com/": "https://www.bing.com/",
    "https://duckduckgo.com/": "https://duckduckgo.com/",
    "https://www.wolframalpha.com/": "https://www.wolframalpha.com/",
    "https://www.mathway.com/": "https://www.mathway.com/",
    "https://www.grammarly.com/": "https://www.grammarly.com/",
    "https://pastebin.com/": "https://pastebin.com/",
    "https://gist.github.com/": "https://gist.github.com/",
    "https://www.calculator.net/": "https://www.calculator.net/",
    "https://www.unitconverters.net/": "https://www.unitconverters.net/",
    "https://www.pdfescape.com/": "https://www.pdfescape.com/",
    "https://smallpdf.com/": "https://smallpdf.com/",
    "https://www.ilovepdf.com/": "https://www.ilovepdf.com/",
    "https://www.zamzar.com/": "https://www.zamzar.com/",
    "https://www.remove.bg/": "https://www.remove.bg/",
    "https://www.canva.com/tools/": "https://www.canva.com/tools/",
    "https://www.trello.com/": "https://www.trello.com/",
    "https://www.notion.so/": "https://www.notion.so/",
    "https://keep.google.com/": "https://keep.google.com/",
    "https://www.evernote.com/": "https://www.evernote.com/",
    "https://www.dropbox.com/": "https://www.dropbox.com/",
    "https://www.send-anywhere.com/": "https://www.send-anywhere.com/",
    "https://wetransfer.com/": "https://wetransfer.com/",
    "https://www.speedtest.net/": "https://www.speedtest.net/",
    "https://www.timeanddate.com/": "https://www.timeanddate.com/",
    "https://www.worldclock.com/": "https://www.worldclock.com/",
    "https://calendar.google.com/": "https://calendar.google.com/",
    "https://www.diffchecker.com/": "https://www.diffchecker.com/",
    "https://regex101.com/": "https://regex101.com/",
    "https://jsonlint.com/": "https://jsonlint.com/",
    "https://www.base64decode.org/": "https://www.base64decode.org/",
    "https://www.base64encode.org/": "https://www.base64encode.org/",
    "https://codebeautify.org/": "https://codebeautify.org/",
    "https://www.online-convert.com/": "https://www.online-convert.com/",
    "https://www.remove.bg/": "https://www.remove.bg/",
    "https://tinypng.com/": "https://tinypng.com/",
    "https://www.photopea.com/": "https://www.photopea.com/",
    "https://www.random.org/": "https://www.random.org/",
    "https://www.lastpass.com/password-generator": "https://www.lastpass.com/password-generator",
    "https://www.qr-code-generator.com/": "https://www.qr-code-generator.com/",
    "https://clipchamp.com/": "https://clipchamp.com/",
    "https://www.calm.com/": "https://www.calm.com/",
    "https://www.bitly.com/": "https://www.bitly.com/",
    "https://www.tinyurl.com/": "https://www.tinyurl.com/",
}

URLS_FILE = "urls.txt"

def find_new_urls(target_url):
    """Crawls a target page and finds new URLs within the same domain."""
    try:
        print(f"Crawling {target_url} for new links...")
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
        response = requests.get(target_url, headers=headers, timeout=10)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')

        found_urls = set()
        base_domain = urlparse(target_url).netloc

        for link in soup.find_all('a', href=True):
            href = link.get('href')
            # Handle different types of links
            full_url = urljoin(target_url, href)
            parsed_url = urlparse(full_url)
            
            # Check for same domain and valid scheme
            if parsed_url.netloc == base_domain and parsed_url.scheme in ['http', 'https']:
                # Clean up the URL by removing fragments (#)
                clean_url = full_url.split('#')[0]
                found_urls.add(clean_url)

        return found_urls
    except requests.exceptions.RequestException as e:
        print(f"Error finding URLs from {target_url}: {e}")
        return set()

def update_urls_file(new_urls):
    """Adds new, unique URLs to the urls.txt file and returns True if a change was made."""
    existing_urls = set()
    if os.path.exists(URLS_FILE):
        with open(URLS_FILE, "r") as f:
            existing_urls = {line.strip() for line in f.readlines()}

    new_and_unique = new_urls - existing_urls

    if new_and_unique:
        print(f"Found {len(new_and_unique)} new unique URLs. Appending to {URLS_FILE}...")
        with open(URLS_FILE, "a") as f:
            for url in sorted(list(new_and_unique)):
                f.write(f"\n{url}")
        return True
    else:
        print("No new unique URLs found. File will not be changed.")
        return False

def main():
    """Main function to discover and update URLs."""
    total_discovered_urls = set()
    for target_url, url_prefix in TARGET_SITES.items():
        discovered_urls = find_new_urls(target_url)
        total_discovered_urls.update(discovered_urls)

    if total_discovered_urls:
        if update_urls_file(total_discovered_urls):
            return 0  # Success, changes made
    return 1  # No changes, nothing to commit

if __name__ == "__main__":
    import sys
    sys.exit(main())
